name: Idea
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like Burny to do?
    validations:
      required: true
